# To get consistent service DNS names kafka-N.broker.kafka (.svc.cluster.local), run everything in a namespace
# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: brokerdns
  namespace: default
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  selector:
    app: kafka
