# kubectl apply -f https://raw.githubusercontent.com/astbss/kafka-kubernetes/master/kafka-testclient.yml
# kubectl apply -f ./kafka-testclient.yml

apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: kafka
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: confluentinc/cp-kafka:5.1.2-2
    # image: confluentinc/cp-kafka:4.1.2-2
    imagePullPolicy: IfNotPresent
    name: kafka
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File

# kubectl -n kafka exec -ti testclient -- bash
    
    
