# mkdir -p /var/kafka/broker ; mkdir -p mkdir -p /var/kafka/pzoo ; chmod -R 777 /var/kafka
# kubectl apply -f PersistentVolume-pzoo.yml
# kubectl get PersistentVolume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datapzoo
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/kafka/pzoo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ansikub
          
# kubectl get PersistentVolume
# kubectl get PersistentVolumeClaims
# kubectl delete PersistentVolumeClaims data-kafka-0
# kubectl delete PersistentVolumeClaims data-pzoo-0
# kubectl delete PersistentVolumeClaim databroker-kafka-0
